-- Base de datos para guardar datos sobre aldeas y las guerras blablabla
-- 15/11/2019
-- Creado por el gran Don Pelayo el Reconquistador

CREATE DATABASE Nervionia
GO

USE Nervionia
GO

CREATE TABLE NEREspecies (
	ID SmallInt Not NULL IDENTITY(1,1),
	NomCientifico VarChar(50) Not Null,
	NomComun VarChar(50) Not NULL,
	Alimentacion VarChar(50) Not NULL,
	Volador Bit Not NULL,
	CONSTRAINT PKNER_Especies PRIMARY KEY (ID)
)
GO

CREATE TABLE NERSeres (
	ID SmallInt Not NULL IDENTITY(1,1),
	IDEspecie SmallInt Not NULL,

	CONSTRAINT PK_Seres PRIMARY KEY (ID),
	CONSTRAINT FK_SeresEspecies FOREIGN KEY (IDEspecie) REFERENCES NERESpecies (ID)
		ON DELETE No Action ON UPDATE Cascade,
	-- IDTribu DONE
)

CREATE TABLE NERSERES_ESCLAVOS (
	IDSer SmallInt Not NULL,
	FechaLibertad Date NULL,

	CONSTRAINT FK_SERES_ESCLAVOS_Seres FOREIGN KEY (IDSer) REFERENCES NERSeres (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT PK_SERES_ESCLAVOS PRIMARY KEY (IDSer)
	)

CREATE TABLE NERTribus (
	ID Smallint Not NULL IDENTITY(1,1),
	Nombre VarChar(50) Not NULL,
	Lema VarChar(140) Not NULL,
	
	CONSTRAINT PK_Tribus PRIMARY KEY (ID)
)
GO

ALTER TABLE NERSeres ADD
	IDTribu SmallInt Not NULL,

	CONSTRAINT FK_SeresTribus FOREIGN KEY (IDTribu) REFERENCES NERTribus (ID)
GO

CREATE TABLE NERReligiones (
	ID SmallInt Not NUll IDENTITY(1,1),
	Nombre VarChar(50) Not NULL,
	Tipo VarChar(70) Not NULL

	CONSTRAINT PK_Religiones PRIMARY KEY (ID)
)
GO

CREATE TABLE NERTRIBUS_RELIGIONES (
	IDTribu SmallInt Not NULL,
	IDReligion SmallInt Not NULL,

	CONSTRAINT FK_Tribus FOREIGN KEY (IDTribu) REFERENCES NERTribus (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Religiones FOREIGN KEY (IDReligion) REFERENCES NERReligiones (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT PK_TRIBUS_RELIGIONES PRIMARY KEY (IDTribu, IDReligion)
)
GO

CREATE TABLE NERSERES_RELIGIONES (
	IDSer SmallInt Not NULL,
	IDReligion SmallInt Not NULL,

	CONSTRAINT FK_SERES_RELIGIONES_Seres FOREIGN KEY (IDSer) REFERENCES NERSeres (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_SERES_RELIGIONES_Religiones FOREIGN KEY (IDReligion) REFERENCES NERReligiones (ID)
		ON DELETE No Action ON UPDATE Cascade,
)

CREATE TABLE NERSacerdotes (
	ID SmallInt Not NULL IDENTITY(1,1),
	IDReligion SmallInt Not NULL,
	Nombre VarChar(70) Not Null,

	CONSTRAINT PK_Sacerdotes PRIMARY KEY (ID),
	CONSTRAINT FK_SacerdotesReligiones FOREIGN KEY (IDReligion) REFERENCES NERReligiones (ID)
		ON DELETE No Action ON UPDATE Cascade
)
GO

CREATE TABLE SERES_ESCLAVOS (
	IDSer SmallInt Not NULL IDENTITY(1,1),
	Fecha Date NULL,

	CONSTRAINT FK_SERES_ESCLAVOSSeres FOREIGN KEY (IDSer) REFERENCES NERSeres (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT PK_SERES_ESCLAVOS PRIMARY KEY (IDSer)
)
GO

CREATE TABLE NERPoblados (
	ID SmallInt Not NULL IDENTITY(1,1),
	Nombre VarChar(50) Not NULL,
	NumHab int Not NULL,
	NumForti int Not NULL,
	Longitud Decimal Not NULL,
	Latitud Decimal Not NULL,
	IDTribu SmallInt Not NULL,

	CONSTRAINT PK_Poblados PRIMARY KEY (ID),
	CONSTRAINT FK_PobladosTribus FOREIGN KEY (IDtribu) REFERENCES NERTribus (ID)
		ON DELETE No Action ON UPDATE Cascade
)
GO

CREATE TABLE NERBatallas (
	ID SmallInt Not NULL IDENTITY(1,1),
	IDPoblado SmallInt Not NULL,
	FechaInicio Date Not NULL,
	FechaFin Date NULL,
	
	CONSTRAINT PK_Batallas PRIMARY KEY (ID),
	CONSTRAINT FK_BatallasPoblados FOREIGN KEY (IDPoblado) REFERENCES NERPoblados (ID)
		ON DELETE No Action ON UPDATE Cascade
)
GO

CREATE TABLE NERGuerras (
	ID SmallInt Not NULL IDENTITY,

	CONSTRAINT PK_Guerras PRIMARY KEY (ID)
)
GO

CREATE TABLE NerBandos (
	ID SmallInt Not NULL IDENTITY(1,1),
	IDGuerra SmallInt Not NULL,
	Nombre VarChar(50) NOt NULL,

	CONSTRAINT PK_Bandos PRIMARY KEY (ID),
	CONSTRAINT FK_BandosGuerras FOREIGN KEY (IDGuerra) REFERENCES NERGuerras (ID)
		ON DELETE No Action ON UPDATE Cascade
)
GO

CREATE TABLE NERBATALLAS_BANDOS (
	IDBatalla SmallInt Not NULL,
	IDBando SmallInt Not NULL,

	CONSTRAINT FK_BATALLAS_BANDOS_Batallas FOREIGN KEY (IDBatalla) REFERENCES NERBatallas (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_BATALLAS_BANDOS_Bandos FOREIGN KEY (IDBando) REFERENCES NERBandos (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT PK_BATALLAS_BANDOS PRIMARY KEY (IDBatalla, IDBando)
)

CREATE TABLE NERBANDOS_TRIBUS (
	IDBando SmallInt Not NULL,
	IDTribu SmallInt Not NULL,

	CONSTRAINT FK_NERBANDOS_TRIBUSBandos FOREIGN KEY (IDBando) REFERENCES NERBandos (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_NERBANDOS_TRIBUSTribus FOREIGN KEY (IDTribu)	REFERENCES NERTribus (ID)
		ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT PK_NERBANDOS_TRIBUS PRIMARY KEY (IDBando, IDTribu)
 )
 GO


